// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsjgkafgxygxoflhwqwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzamdrYWZneHlneG9mbGh3cXd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTk5NzcsImV4cCI6MjA2OTczNTk3N30.fMvswB5urPsD_wpy502AVdOOwO_5SZXu29D5NanF1TQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});